language: ruby
rvm:
  - 2.0.0
script:
  - bundle exec rake db:drop db:create db:migrate
  - CODECLIMATE_REPO_TOKEN=f32c483f885a26107647bfb782270b0e4e32368d42aa3a20c2cbe60bfcbc0e19 bundle exec rake
  - bundle exec rspec
deploy:
  curl -X POST "https://j.pyar.bz/job/PhotoWander_production/build?token=TZxKK2UQCUD2ww6umeMzqwHDYfhJ3s"
